name = "vdb"
version = "0.0.1"
maintainer = "vdb contributors"
license = "MIT"
author = "左志华"
categories = "fpm auxiliary program"
copyright = "Copyright (c) 左志华"


[dependencies]
[dependencies.M_attr]
git = "https://github.com/urbanjost/M_attr.git"
rev = "608b9d3b40be9ff2590c23d2089781fd4da76344"

[dependencies.json-fortran]
git = "https://github.com/jacobwilliams/json-fortran"
rev = "77c9f99d7d5c6a0ec9011f7225db3dbb6894ef6d"

[dependencies.dp-stdlib]
git = "https://github.com/zoziha/dp-stdlib"
rev = "d317f4d273cb0fcabf532578a7ec0e4687e18700"

[dev-dependencies]
[dev-dependencies.test-drive]
git = "https://github.com/fortran-lang/test-drive"
rev = "9c3401e30dbd2da1add77aaa252a4c6928fe39a1"
