name = "vdb"
version = "0.0.1"
maintainer = "vdb contributors"
license = "MIT"
author = "左志华"
categories = "fpm auxiliary program"
copyright = "Copyright (c) 左志华"

[dependencies]
[dependencies.json-fortran]
git = "https://github.com/jacobwilliams/json-fortran"
rev = "77c9f99d7d5c6a0ec9011f7225db3dbb6894ef6d"

[dependencies.stdlib]
git = "https://github.com/fortran-lang/stdlib"
rev = "f9e7853a09a1d1bdfdea2c6a782e8775d8c47c66"

[dependencies.forlab]
git = "https://github.com/fortran-fans/forlab.git"
rev = "f82ffe606bd37071dc8142a91f22bfb2dbdbe87a"

[dev-dependencies]
[dev-dependencies.test-drive]
git = "https://github.com/fortran-lang/test-drive"
rev = "9c3401e30dbd2da1add77aaa252a4c6928fe39a1"
