name = "vdb"
version = "0.1.0"
maintainer = "vdb contributors"
license = "MIT"
author = "左志华"
categories = "fpm auxiliary program"
copyright = "Copyright (c) 左志华"


[dependencies]

stdlib_string_type = { git = "https://github.com/degawa/stdlib_modules", branch = "stdlib_string_type-fpm" }
stdlib_strings = { git = "https://github.com/degawa/stdlib_modules", branch = "stdlib_strings-fpm" }
stdlib_ascii = { git = "https://github.com/degawa/stdlib_modules", branch = "stdlib_ascii-fpm" }

[dependencies.M_attr]
git = "https://github.com/urbanjost/M_attr.git"
rev = "608b9d3b40be9ff2590c23d2089781fd4da76344"

[dependencies.json-fortran]
git = "https://github.com/jacobwilliams/json-fortran"
rev = "77c9f99d7d5c6a0ec9011f7225db3dbb6894ef6d"


[dev-dependencies]
[dev-dependencies.test-drive]
git = "https://github.com/fortran-lang/test-drive"
rev = "9c3401e30dbd2da1add77aaa252a4c6928fe39a1"
